In [ ]:
import cv2
import pandas as pd

# Read image
img = cv2.imread('butterfly.jpg')

# Check image loaded
if img is None:
    print("Image not found")
else:
    

    # Convert image pixels into rows
    pixels = img.reshape(-1, 3)

    # Create DataFrame with BGR values
    df = pd.DataFrame(
        pixels,
        columns=['Blue', 'Green', 'Red']
    )

    # Save to Excel
    df.to_excel(
        'pixel_values.xlsx',
        index=False
    )

    print("Pixel values saved to Excel")

[[[212 172 153]
  [212 172 153]
  [212 172 153]
  ...
  [200 152 124]
  [200 152 124]
  [200 152 124]]

 [[212 172 153]
  [212 172 153]
  [212 172 153]
  ...
  [200 152 124]
  [200 152 124]
  [200 152 124]]

 [[212 172 153]
  [212 172 153]
  [212 172 153]
  ...
  [200 152 124]
  [200 152 124]
  [200 152 124]]

 ...

 [[144 203 243]
  [131 190 230]
  [115 174 214]
  ...
  [138 185 217]
  [139 186 218]
  [141 188 220]]

 [[111 170 210]
  [104 163 203]
  [101 160 200]
  ...
  [144 191 223]
  [145 192 224]
  [146 193 225]]

 [[136 197 237]
  [122 183 223]
  [116 175 215]
  ...
  [148 197 229]
  [149 196 228]
  [150 197 229]]]
